# Generated by Django 5.1.4 on 2025-09-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_featured_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_on"]},
        ),
    ]
